name: Java CI with Maven # Workflow-namn: Identifierar denna workflow i GitHub Actions.

# Anger när workflowen ska köras: Triggas vid push eller pull request till "main"-grenen.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Definierar jobb i workflowen
jobs:
  build:
    runs-on: ubuntu-latest     # Anger att jobbet ska köras på en virtuell maskin med Ubuntu.

    permissions:     # Ger  behörigheter för att komma åt repot.
      contents: write

    steps:
    - uses: actions/checkout@v4     # Checkar ut repositorys källkod till den virtuella maskinen.
    - name: Set up JDK 22      # Installerar JDK 22 med Temurin-distributionen.
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven # Cacher Maven-beroenden för att snabba upp framtida byggningar.

    - name: Build and Test with Maven  # Bygger projektet med Maven och kör testerna.
      run: mvn -B clean package # Använder `clean` för att rensa gamla byggfiler och `package` för att bygga projektet.
